modLoader = "javafml"
loaderVersion = "${loader_range}"
license = "MIT"
issueTrackerURL = "https://github.com/${github_project}/issues"

[[mods]]
modId = "create_tweaked_controllers"
version = "${version}"
displayName = "Create: Tweaked Controllers"
displayURL="https://github.com/${github_project}"
logoFile = "logo.png"
authors = "getItemFromBlock"
description = '''
A Create Addon that adds a way of controlling contraptions using an advanced controller.
Compatible with Create 0.5.1+
'''

[[dependencies.create_tweaked_controllers]]
modId = "forge"
mandatory = true
versionRange = "${forge_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_tweaked_controllers]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.create_tweaked_controllers]]
modId = "create"
mandatory = true
versionRange = "${create_range}"
ordering = "NONE"
side = "BOTH"